permissions:
  contents: write

name: Build binaries
on:
  push:
    tags:
      - "v**"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: README.md
          output_dir: README.pdf
          build_html: false
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
